# Site settings
title: GMU IEEE | George Mason University Institute of Electrical and Electronics Engineers
description: "Our vision is to advance GMU engineering to the forefronts of technological innovation through applied research and networking"
url: "ieee-gmu.github.io"
author:
  name: "GMU IEEE"
  email: "ieee.gmu@gmail.com"
  url: "https://getconnected.gmu.edu/organization/inst-of-electrical-and-electronics-engineers"

# Build settings
baseurl: /emerald # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
